version: 2

models:
  - name: fct_orders
    description: Fact table containing order line items with product and customer details
    columns:
      - name: order_id
        description: Order identifier
        tests:
          - not_null
      - name: customer_id
        description: Customer who placed the order
        tests:
          - not_null
      - name: product_id
        description: Product in the order
        tests:
          - not_null
      - name: order_purchase_timestamp
        description: When the order was placed
      - name: product_category_name
        description: Category of the product
      - name: price
        description: Item price in BRL
        tests:
          - not_null
      - name: freight_value
        description: Shipping cost in BRL
      - name: total_order_value
        description: Price + freight combined
        tests:
          - not_null

  - name: dim_customers
    description: Customer dimension with lifetime value and classification
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: Unique ID for the same customer across orders
        tests:
          - not_null
      - name: state
        description: Customer state (2-letter code)
      - name: total_orders
        description: Number of orders placed
      - name: lifetime_value
        description: Total revenue from this customer
      - name: customer_type
        description: Classification - Returning, One-time, or No Orders
        tests:
          - accepted_values:
              values: ['Returning', 'One-time', 'No Orders']

  - name: dim_products
    description: Product dimension with sales metrics and tier classification
    columns:
      - name: product_id
        description: Unique product identifier
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: Category name in Portuguese
      - name: times_sold
        description: Number of times this product was sold
      - name: total_revenue
        description: Total revenue from this product
      - name: sales_tier
        description: Classification based on sales volume
        tests:
          - accepted_values:
              values: ['High Seller', 'Medium Seller', 'Low Seller', 'Never Sold']

  - name: dim_sellers
    description: Seller dimension with performance metrics and tier
    columns:
      - name: seller_id
        description: Unique seller identifier
        tests:
          - unique
          - not_null
      - name: state
        description: Seller state location
      - name: total_orders
        description: Number of orders fulfilled
      - name: total_revenue
        description: Total revenue generated
      - name: avg_review_score
        description: Average customer review score (1-5)
      - name: seller_tier
        description: Revenue-based tier classification
        tests:
          - accepted_values:
              values: ['Platinum', 'Gold', 'Silver', 'Bronze']
