version: 2

models:
  - name: stg_orders
    description: Cleaned orders data with standardized column names
    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to customers table
        tests:
          - not_null
      - name: order_status
        description: Current status of the order (delivered, shipped, canceled, etc.)
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'unavailable', 'invoiced', 'processing', 'created', 'approved']
      - name: order_purchase_timestamp
        description: Timestamp when the order was placed
        tests:
          - not_null

  - name: stg_customers
    description: Cleaned customer data with location information
    columns:
      - name: customer_id
        description: Unique identifier for each customer record
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: Unique identifier for a customer across multiple orders
        tests:
          - not_null
      - name: zip_code
        description: Customer's zip code prefix
      - name: city
        description: Customer's city
      - name: state
        description: Customer's state (2-letter code)
        tests:
          - not_null

  - name: stg_order_items
    description: Line items for each order with pricing details
    columns:
      - name: order_id
        description: Foreign key to orders table
        tests:
          - not_null
      - name: item_sequence_number
        description: Sequential number of the item within the order
        tests:
          - not_null
      - name: product_id
        description: Foreign key to products table
        tests:
          - not_null
      - name: seller_id
        description: Foreign key to sellers table
        tests:
          - not_null
      - name: price
        description: Price of the item in Brazilian Real (BRL)
        tests:
          - not_null
      - name: freight_value
        description: Shipping cost for the item in BRL

  - name: stg_products
    description: Product catalog with dimensions and category
    columns:
      - name: product_id
        description: Unique identifier for each product
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: Category of the product (in Portuguese)
      - name: product_weight_g
        description: Product weight in grams
      - name: product_length_cm
        description: Product length in centimeters
      - name: product_height_cm
        description: Product height in centimeters
      - name: product_width_cm
        description: Product width in centimeters

  - name: stg_payments
    description: Payment information for orders
    columns:
      - name: order_id
        description: Foreign key to orders table
        tests:
          - not_null
      - name: payment_sequential
        description: Sequential number for multiple payments on same order
        tests:
          - not_null
      - name: payment_type
        description: Payment method used
        tests:
          - not_null
          - accepted_values:
              values: ['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
      - name: payment_installments
        description: Number of installments for the payment
      - name: payment_value
        description: Payment amount in BRL
        tests:
          - not_null
