version: 2

sources:
  - name: raw_olist
    description: Raw data from Olist E-commerce dataset
    database: olist_analytics
    schema: raw_olist
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: products     
      - name: order_payments
      - name: sellers
      - name: geolocation
      - name: order_reviews
      - name: category_translation